- name: reconfig buildbot winworker
  template:
    src: 'worker.yml.j2'
    dest: '{{ hostvars[buildbot_master_host].buildbot_master_workers_path }}/{{ buildbot_worker_name }}.yml'
  become: yes
  become_user: '{{ hostvars[buildbot_master_host].buildbot_master_user }}'
  delegate_to: '{{ buildbot_master_host }}'
  notify:
  - reconfigure buildbot master
